Repository AlchemyCMS/alchemy_cms, pull requests merged in 2022-04, with the labels that each got.

#2210 Support AR enums in resource models
  app/views/alchemy/admin/resources/_form.html.erb
  lib/alchemy/resource.rb
  spec/dummy/app/models/event.rb
  spec/dummy/config/locales/en.yml
  spec/dummy/db/migrate/20211105175532_add_event_type_to_events.rb
  spec/dummy/db/schema.rb
  spec/features/admin/resources_integration_spec.rb
Labels: needs tests

#2315 Fix gif resizing
  app/models/alchemy/picture/transformations.rb
  config/initializers/dragonfly.rb
  lib/alchemy/dragonfly/processors/thumbnail.rb
  spec/libraries/dragonfly/processors/thumbnail_spec.rb
Labels: needs backport

#2323 Remove JSON decode from ingredient data store
  app/models/alchemy/ingredient.rb
Labels: bug
