Repository AlchemyCMS/alchemy_cms, pull requests merged in 2023-05, with the labels that each got.

#2470 Do not render nested elements of element editor if folded
  app/views/alchemy/admin/elements/_element.html.erb
Labels: needs backport

#2472 Revert "Preload related objects in Alchemy::PagesController"
  app/controllers/alchemy/pages_controller.rb
Labels: needs backport

#2462 Use ISO Date format in flatpickr
  package/src/datepicker.js
Labels: needs tests, needs backport

#2389 Fix page seeder
  lib/alchemy/seeder.rb
  spec/features/page_seeder_spec.rb
  spec/fixtures/pages.yml
Labels: bug, confirmed, needs backport
