Repository AlchemyCMS/alchemy_cms, pull requests merged in 2023-09, with the labels that each got.

#2556 Picture Ingredient: Fix NaN error with free height
  app/models/concerns/alchemy/picture_thumbnails.rb
  lib/alchemy/test_support/having_picture_thumbnails_examples.rb
Labels: backport-to-7.0-stable, backport-to-6.1-stable

#2521 Copying pages: Only add "(Copy)" if necessary
  app/models/alchemy/page.rb
  app/services/alchemy/copy_page.rb
  spec/models/alchemy/page_spec.rb
  spec/services/alchemy/copy_page_spec.rb
Labels: feature

#2586 Disable Turbo on the leave overlay
  app/views/alchemy/admin/leave.html.erb
Labels: backport-to-7.0-stable
