Repository AlchemyCMS/alchemy_cms, pull requests merged in 2023-08, with the labels that each got.

#2539 Improve Richtext editor view
  app/models/alchemy/ingredients/richtext.rb
  app/views/alchemy/ingredients/_richtext_editor.html.erb
  spec/models/alchemy/ingredients/richtext_spec.rb
Labels: backport, 7.0-stable

#2559 Allow redirecting to other host in site redirect
  app/controllers/concerns/alchemy/site_redirects.rb
  spec/requests/alchemy/site_requests_spec.rb
Labels: bug, backport, 7.0-stable, 6.1-stable

#2560 Add backport GH action
  .github/workflows/backport.yml
Labels: backport, test-branch

#2561 Change backport templates
  .github/workflows/backport.yml
Labels: confirmed, Documentation, backport test-branch

#2563 Change capitalization of Ruby On Rails in README
  README.md
Labels: confirmed, Documentation, backport test-branch

#2564 Actions: Remove labels_template
  .github/workflows/backport.yml
Labels: backport test-branch

#2566 Revert "Change capitalization of Ruby On Rails in README"
  README.md
Labels: backport test-branch

#2567 Use sqren/backport for automated back porting of PRs
  .github/workflows/backport.yml
Labels: backport-to-test-branch

#2571 Fix NonStupidDigestAssets with String whitelist
  lib/non_stupid_digest_assets.rb
  spec/libraries/non_stupid_digest_assets_spec.rb
Labels: bug, backport-to-7.0-stable, backport-to-6.1-stable
