Repository AlchemyCMS/alchemy_cms, pull requests merged in 2023-04, with the labels that each got.

#2454 Allow editors to switch language
  lib/alchemy/permissions.rb
  spec/libraries/permissions_spec.rb
Labels: needs backport

#2455 Fix picture file format filter
  app/models/alchemy/picture.rb
  config/locales/alchemy.en.yml
  spec/models/alchemy/picture_spec.rb
Labels: bug, needs backport

#2456 Fix picture show overlay if picture in use
  app/views/alchemy/admin/pictures/_infos.html.erb
  spec/views/admin/pictures/show_spec.rb
Labels: bug
