Repository AlchemyCMS/alchemy_cms, pull requests merged in 2023-06, with the labels that each got.

#2459 Fix layoutpages configuration
  app/views/alchemy/admin/pages/update.js.erb
Labels: bug, confirmed, needs backport

#2487 Add ransackable attributes to tags
  app/controllers/alchemy/admin/tags_controller.rb
  app/models/alchemy/tag.rb
  spec/controllers/alchemy/admin/tags_controller_spec.rb
  spec/dummy/app/models/series.rb
Labels: bug

#2504 Allow authors to link to all pages again
  app/assets/javascripts/alchemy/alchemy.link_dialog.js.coffee
  app/controllers/alchemy/api/pages_controller.rb
  app/views/alchemy/ingredients/shared/_link_tools.html.erb
  app/views/alchemy/ingredients/shared/_picture_tools.html.erb
  lib/alchemy/permissions.rb
  spec/controllers/alchemy/api/pages_controller_spec.rb
  spec/features/admin/link_overlay_spec.rb
Labels: needs backport

#2507 Allow to create element with warning in definition
  app/models/alchemy/element.rb
  spec/dummy/config/alchemy/elements.yml
  spec/models/alchemy/element_spec.rb
Labels: needs backport
