Repository AlchemyCMS/alchemy_cms, pull requests merged in 2024-07, with the labels that each got.

#2951 Fix re-render of layoutpages form if validation fails
  app/controllers/alchemy/admin/layoutpages_controller.rb
  app/views/alchemy/admin/layoutpages/edit.html.erb
  config/routes.rb
  lib/alchemy/permissions.rb
  spec/controllers/alchemy/admin/layoutpages_controller_spec.rb
  spec/libraries/permissions_spec.rb
Labels: bug, backport-to-7.0-stable, backport-to-7.1-stable, backport-to-7.2-stable

#2959 Remove call to missing content_positions task
  lib/tasks/alchemy/tidy.rake
Labels: backport-to-7.0-stable, backport-to-7.1-stable, backport-to-7.2-stable

#2965 Update _autocomplete_tag_list.html.erb
  app/views/alchemy/admin/partials/_autocomplete_tag_list.html.erb
Labels: bug, backport-to-7.2-stable

#2964 Fix picture selector behavior
  app/javascript/alchemy_admin/picture_selector.js
  app/views/alchemy/admin/pictures/index.html.erb
  spec/javascript/alchemy_admin/picture_selector.spec.js
Labels: backport-to-7.2-stable

#2957 Clear current language when switching sites
  app/controllers/concerns/alchemy/admin/current_language.rb
  lib/alchemy/test_support/current_language_shared_examples.rb
  spec/controllers/alchemy/admin/layoutpages_controller_spec.rb
  spec/controllers/alchemy/admin/nodes_controller_spec.rb
  spec/controllers/alchemy/admin/pages_controller_spec.rb
  spec/rails_helper.rb
Labels: backport-to-7.1-stable, backport-to-7.2-stable

#2978 Fix combining search filters and pagination
  app/views/alchemy/admin/resources/_per_page_select.html.erb
  spec/features/admin/resources_integration_spec.rb
Labels: backport-to-7.0-stable, backport-to-6.1-stable, backport-to-7.1-stable, backport-to-7.2-stable
