Repository AlchemyCMS/alchemy_cms, pull requests merged in 2024-04, with the labels that each got.

#2820 Fix module error
  lib/alchemy/modules.rb
  spec/libraries/modules_spec.rb
Labels: backport-to-7.0-stable, backport-to-7.1-stable

#2829 Nullify Ingredients::Page on Page destroy
  app/models/alchemy/page.rb
  spec/models/alchemy/page_spec.rb
Labels: backport-to-7.0-stable, backport-to-7.1-stable

#2836 Fix Ingredient Boolean View
  app/components/alchemy/ingredients/boolean_view.rb
Labels: bug, backport-to-7.0-stable, backport-to-7.1-stable

#2844 UI fixes for picture css class display
  app/assets/stylesheets/alchemy/elements.scss
Labels: bug, backport-to-7.1-stable
