Repository AlchemyCMS/alchemy_cms, pull requests merged in 2024-02, with the labels that each got.

#2714 Fix ActionNotFound in PictureController
  app/controllers/alchemy/admin/pictures_controller.rb
Labels: backport-to-7.1-stable

#2728 Fix overlay picture grid
  app/assets/stylesheets/alchemy/archive.scss
Labels: backport-to-7.1-stable

#2735 Fix tags view for missing taggables
  app/assets/stylesheets/alchemy/labels.scss
  app/views/alchemy/admin/tags/_tag.html.erb
  spec/controllers/alchemy/admin/tags_controller_spec.rb
Labels: backport-to-7.0-stable, backport-to-7.1-stable

#2741 Fix svg thumbnail size
  app/assets/stylesheets/alchemy/archive.scss
Labels: backport-to-7.1-stable

#2689 Fixes language switching to default language
  app/controllers/alchemy/admin/languages_controller.rb
  app/controllers/concerns/alchemy/admin/current_language.rb
  lib/alchemy/controller_actions.rb
  spec/controllers/alchemy/pages_controller_spec.rb
  spec/helpers/alchemy/base_helper_spec.rb
  spec/libraries/controller_actions_spec.rb
Labels: backport-to-7.0-stable, backport-to-7.1-stable

#2750 Fix sortable elements
  app/javascript/alchemy_admin/sortable_elements.js
  app/views/alchemy/admin/elements/create.js.erb
Labels: bug, backport-to-7.1-stable

#2752 Fix order of elements after Page copy
  app/models/alchemy/page/page_elements.rb
  spec/models/alchemy/page_spec.rb
Labels: bug, backport-to-7.0-stable, backport-to-6.1-stable, backport-to-7.1-stable

#2734 Fix two minor translations
  config/locales/alchemy.en.yml
Labels: backport-to-7.1-stable

#2760 Fix datepicker in resource forms
  lib/alchemy/forms/builder.rb
  lib/alchemy/resources_helper.rb
  spec/features/admin/resources_integration_spec.rb
  spec/libraries/forms/builder_spec.rb
  spec/libraries/resources_helper_spec.rb
Labels: bug, backport-to-7.1-stable

#2761 Fix taggable uniqueness in tags admin table
  app/views/alchemy/admin/tags/_tag.html.erb
  spec/features/admin/tags_integration_spec.rb
Labels: bug, backport-to-7.0-stable, backport-to-7.1-stable
