Repository AlchemyCMS/alchemy_cms, pull requests merged in 2024-06, with the labels that each got.

#2909 fix Ingredient Audio and Video boolean type casting
  app/models/alchemy/ingredients/audio.rb
  app/models/alchemy/ingredients/video.rb
  spec/models/alchemy/ingredients/audio_spec.rb
  spec/models/alchemy/ingredients/video_spec.rb
Labels: backport-to-7.0-stable, backport-to-7.1-stable, backport-to-7.2-stable

#2913 fix(RoutingConstraints): Allow Turbo Stream requests
  lib/alchemy/routing_constraints.rb
  spec/routing/routing_spec.rb
Labels: bug, backport-to-7.0-stable, backport-to-7.1-stable, backport-to-7.2-stable

#2917 Replace picture css class after update
  app/assets/stylesheets/alchemy/elements.scss
  app/views/alchemy/admin/ingredients/_picture_fields.html.erb
  app/views/alchemy/admin/ingredients/update.turbo_stream.erb
  app/views/alchemy/ingredients/_picture_editor.html.erb
  app/views/alchemy/ingredients/shared/_picture_css_class.html.erb
Labels: backport-to-7.2-stable

#2918 Enable element select if only one is available
  app/views/alchemy/admin/elements/_form.html.erb
Labels: backport-to-7.2-stable

#2919 Fix clipboard items styling
  app/assets/stylesheets/alchemy/clipboard.scss
  app/views/alchemy/admin/clipboard/index.html.erb
Labels: backport-to-7.2-stable

#2926 fix(ContactMessages): Use alchemy route proxy
  app/controllers/alchemy/messages_controller.rb
Labels: backport-to-7.0-stable, backport-to-7.1-stable, backport-to-7.2-stable

#2944 Disable Turbo Prefetch in Admin
  app/views/layouts/alchemy/admin.html.erb
Labels: bug, backport-to-7.2-stable

#2942 Prevent Javascript error if the page will be unlocked
  app/views/alchemy/admin/pages/unlock.js.erb
Labels: bug, backport-to-7.1-stable, backport-to-7.2-stable
