Repository AlchemyCMS/alchemy_cms, pull requests merged in 2025-01, with the labels that each got.

#3110 Fix image_overlay hidden form style
  app/assets/builds/alchemy/admin.css
  app/assets/builds/alchemy/admin.css.map
  app/stylesheets/alchemy/admin/image_library.scss
Labels: backport-to-7.3-stable

#3122 CI: Run actions on ubuntu-22.04
  .github/workflows/backport.yml
  .github/workflows/brakeman-analysis.yml
  .github/workflows/build_test.yml
  .github/workflows/lint.yml
  .github/workflows/stale.yml
  Gemfile
Labels: backport-to-7.0-stable, backport-to-7.1-stable, backport-to-7.2-stable, backport-to-7.3-stable, backport-to-7.4-stable

#3129 Use safe redirect paths in admin redirects
  app/controllers/alchemy/admin/base_controller.rb
  app/controllers/alchemy/admin/languages_controller.rb
  app/controllers/alchemy/admin/pages_controller.rb
  app/controllers/alchemy/admin/resources_controller.rb
  spec/controllers/alchemy/admin/base_controller_spec.rb
Labels: backport-to-7.0-stable, backport-to-7.1-stable, backport-to-7.2-stable, backport-to-7.3-stable, backport-to-7.4-stable

#3032 Allow Rails 8.0
  .github/workflows/build_test.yml
  .github/workflows/lint.yml
  Gemfile
  alchemy_cms.gemspec
  config/routes.rb
  spec/dummy/config/application.rb
  spec/dummy/db/schema.rb
  spec/libraries/forms/builder_spec.rb
Labels: backport-to-7.4-stable

#3139 CI: Set workflow permissions
  .github/workflows/backport.yml
  .github/workflows/brakeman-analysis.yml
  .github/workflows/build_test.yml
  .github/workflows/lint.yml
  .github/workflows/stale.yml
Labels: backport-to-7.0-stable, backport-to-7.1-stable, backport-to-7.2-stable, backport-to-7.3-stable, backport-to-7.4-stable

#3148 Fix Alchemy Guides links
  app/views/alchemy/welcome.html.erb
  lib/generators/alchemy/install/files/alchemy.en.yml
  lib/generators/alchemy/install/templates/menus.yml.tt
  lib/generators/alchemy/install/templates/page_layouts.yml.tt
Labels: backport-to-7.4-stable

#3153 fix attribute sorting across Ruby versions
  lib/alchemy/resource.rb
  spec/libraries/resource_spec.rb
Labels: backport-to-7.1-stable, backport-to-7.2-stable, backport-to-7.3-stable, backport-to-7.4-stable

#3172 Remove coffee-rails dependency
  alchemy_cms.gemspec
Labels: backport-to-7.4-stable

#3176 fix(Uploader): Handle HTML Errors during upload
  app/javascript/alchemy_admin/components/uploader/file_upload.js
  spec/javascript/alchemy_admin/components/uploader/file_upload.spec.js
Labels: backport-to-7.4-stable
